=== MuhamadRifan/Tugas-Xsd/JasaParkir.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsixml"/>
    <xs:element name="JasaParkir">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="alamat"/>
                <xs:element ref="Alamat"/>
                <xs:element ref="GolonganKendaraan"/>
                <xs:element ref="Jenis"/>
                <xs:element ref="KeteranganSTNK"/>
                <xs:element ref="NomorKendaraan"/>
                <xs:element ref="email"/>
                <xs:element ref="jeniskelamin"/>
                <xs:element ref="nama"/>
            </xs:choice>
            <xs:attribute name="Data" use="required" type="xs:NCName"/>
            <xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Alamat">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alamat"/>
            </xs:sequence>
            <xs:attribute name="parkir" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="GolonganKendaraan" type="xs:integer"/>
    <xs:element name="Jenis" type="xs:NCName"/>
    <xs:element name="KeteranganSTNK" type="xs:NCName"/>
    <xs:element name="NomorKendaraan" type="xs:string"/>
    <xs:element name="email" type="xs:string"/>
    <xs:element name="jeniskelamin" type="xs:NCName"/>
    <xs:element name="nama" type="xs:string"/>
    <xs:element name="alamat">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="alamat"/>
            </xs:sequence>
            <xs:attribute name="parkir"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MuhamadRifan/Tugas-Xsd/JasaParkir.xml
<?xml version="1.0" encoding="UTF-8"?>
<JasaParkir xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="JasaParkir.xsd">

	<nama>Muhamad Rifan</nama>
	<NomorKendaraan>Z 1933 BD</NomorKendaraan>
	<GolonganKendaraan>2</GolonganKendaraan>
	<Jenis>Avanza</Jenis>
	<KeteranganSTNK>Ya</KeteranganSTNK>
	<jeniskelamin>laki-Laki</jeniskelamin>
	<alamat>Tasikmalaya</alamat>
	<email>muhamadrifanzamaludin@gmail.com</email>
	<Alamat parkir="Bandung Indah Plaza">
		<alamat>jalan Wastukencana Bandung</alamat>
	</Alamat>
	
	<nama>Achmad Fatahilal</nama>
	<NomorKendaraan>B 9873 BDO</NomorKendaraan>
	<GolonganKendaraan>2</GolonganKendaraan>
	<Jenis>Mobilio</Jenis>
	<KeteranganSTNK>Ya</KeteranganSTNK>
	<jeniskelamin>laki-Laki</jeniskelamin>
	<alamat>Bekasi</alamat>
	<email>achmadganteng@gmail.com</email>
	<Alamat parkir="Bandung Indah Plaza">
		<alamat>jalan Wastukencana Bandung</alamat>
	</Alamat>
	
	<nama>Agus</nama>
	<NomorKendaraan>BG 7540 KL</NomorKendaraan>
	<GolonganKendaraan>2</GolonganKendaraan>
	<Jenis>Agya</Jenis>
	<KeteranganSTNK>Ya</KeteranganSTNK>
	<jeniskelamin>laki-Laki</jeniskelamin>
	<alamat>Palembang</alamat>
	<email>agusiki@gmail.com</email>
	<Alamat parkir="Bandung Indah Plaza">
		<alamat>jalan Wastukencana Bandung</alamat>
	</Alamat>
	
	<nama>yoga ryan</nama>
	<NomorKendaraan>B 1100 DTG</NomorKendaraan>
	<GolonganKendaraan>2</GolonganKendaraan>
	<Jenis>Avanza</Jenis>
	<KeteranganSTNK>Ya</KeteranganSTNK>
	<jeniskelamin>laki-Laki</jeniskelamin>
	<alamat>Tasikmalaya</alamat>
	<email>ryanjombang@gmail.com</email>
	<alamat parkir="Bandung Indah Plaza">
		<alamat>jalan Wastukencana Bandung</alamat>
	</alamat>
	
		<nama>Kharisma Soraya</nama>
	<NomorKendaraan>Z 1357 BD</NomorKendaraan>
	<GolonganKendaraan>2</GolonganKendaraan>
	<Jenis>Avanza</Jenis>
	<KeteranganSTNK>Ya</KeteranganSTNK>
	<jeniskelamin>Perempuan</jeniskelamin>
	<alamat>Tasikmalaya</alamat>
	<email>Sorayakharisma@gmail.com</email>
	<alamat parkir=" Indah Plaza">
		<alamat>jalan Wastukencana Bandung</alamat>
	</alamat>
	</JasaParkir>
